# -*- coding: utf-8 -*-
"""Copia de Correo diario recomendaciones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nDp-Lr7MYdGepm1AsBEmY2xYpVmS0Cf-
"""
import os
import openai
import google.generativeai as genai
import smtplib
import re
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

def validar_credencial(valor, nome):
    if not valor:
        raise ValueError(f"Erro: {nome} não está definido nas variáveis de ambiente.")
    return valor

# Función para obtener noticias de tecnología
def obtener_recomendaciones(prompt, usar_openai=False):
    try:
        if usar_openai:
            response = openai.chat.completions.create(
                model="gpt-3.5-turbo",
                messages=[
                    {"role": "system", "content": "Eres un experto sistema recomendador."},
                    {"role": "user", "content": prompt}
                ]
            )
            return response.choices[0].message.content
        else:
            response = genai.GenerativeModel("gemini-2.0-flash-001").generate_content(prompt)
            return response.text
    except Exception as e:
        print(f"Erro ao obter recomendações: {e}")
        return "Não foi possível obter recomendações no momento."

def formatear_texto_a_html(texto):
    """
    Convierte texto en formato Markdown (**negrita**) a HTML (<b>negrita</b>).
    """
    texto_html = re.sub(r"\*\*(.*?)\*\*", r"<b>\1</b>", texto)  # Convierte **texto** a <b>texto</b>
    return texto_html.replace("\n", "<br>")  # Reemplaza saltos de línea con <br> en HTML

# Función para enviar el correo
def enviar_correo(recomendacion):
    msg = MIMEMultipart()
    msg["From"] = EMAIL_REMITE
    msg["To"] = EMAIL_DESTINO
    msg["Subject"] = "Recomendaciones sobre música, comida y libros"

    # Convertir el mensaje con formato HTML
    recomendacion_html = formatear_texto_a_html(recomendacion)
    cuerpo_mensaje = f"""
    <html>
    <body>
        <p>Hola,</p>
        <p>Aquí tienes la recomendación:</p>
        <p>{recomendacion_html}</p>
        <p>Saludos.</p>
    </body>
    </html>
    """

    msg.attach(MIMEText(cuerpo_mensaje, "html"))

    try:
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(EMAIL_REMITE, EMAIL_PASSWORD)
        server.sendmail(EMAIL_REMITE, EMAIL_DESTINO, msg.as_string())
        server.quit()
        print("Correo enviado exitosamente.")
    except smtplib.SMTPException as e:
        print(f"Erro ao enviar o e-mail: {e}")
    except Exception as e:
        print(f"Erro inesperado ao enviar e-mail: {e}")

OPENAI_API_KEY = validar_credencial(os.getenv("OPENAI_API_KEY"), "OPENAI_API_KEY")
genai.configure(api_key=validar_credencial(os.getenv("GENAI_API_KEY"), "GENAI_API_KEY"))
EMAIL_REMITE = validar_credencial("automatizacionesrrzzalejandro@gmail.com", "EMAIL_REMITE")
EMAIL_DESTINO = validar_credencial("rrzzalejandro@gmail.com", "EMAIL_DESTINO")
EMAIL_PASSWORD = validar_credencial(os.getenv("EMAIL_PASSWORD"), "EMAIL_PASSWORD")


# Ejecutar funciones
prompt = (
        "Actua como el mejor periodista del mundo. Escribe 3 apartados de recomendaciones, sin añadir ninguna introducción, solo los 3 apartados:\n"
        "1. Musicales: tres artistas y dos canciones por cada artista, teniendo en cuenta que mis gustos son: pop, rock pop, rock,  flamenco, indie, reggaeton o música latina pero más comercial...\n"
        "2. Alimentaria: 3 recetas y la lista de ingredientes de cada una. Si tienes acceso a internet, calcula cuanto costaría realizar la receta en base a los precios de los productos en el Mercadona.\n"
        "3. Lectora: dos libros y sus autores, teniendo en cuenta que mis gustos son: novelas, novelas históricas, thriller, policíacas, de desarrollo personal. Además, incluye un breve sinopsis. Si tienes acceso a internet, añade la puntuación del libro en Amazon y su precio \n"
        "Cada sección debe estar bien diferenciada con un título. No deben ser secciones extensas, quiero que se pueda leer en 10 minutos como máximo. Deben estar escritas en español, en un tono sencillo y conciso. Utiliza puntos para separar las noticias. Además, evita repetir las respuestas. Cada semana te haré dos peticiones.\n"
    )

tipo_modelo = False
recomendacion = obtener_recomendaciones(prompt, usar_openai=tipo_modelo)
enviar_correo(recomendacion)
